export type Line = {
  displayName: string
  colour: string
};

export const Lines = {
  bakerloo: {
    displayName: "Bakerloo",
    colour: "#a45a2a",
  },
  central: {
    displayName: "Central",
    colour: "#da291c",
  },
  circle: {
    displayName: "Circle",
    colour: "#ffcd00",
  },
  district: {
    displayName: "District",
    colour: "#007a33",
  },
  hammersmithAndCity: {
    displayName: "Hammersmith & City",
    colour: "#e89cae",
  },
  jubilee: {
    displayName: "Jubilee",
    colour: "#7c878e"
  },
  metropolitan: {
    displayName: "Metropolitan",
    colour: "#840b55"
  },
  northern: {
    displayName: "Northern",
    colour: "#000000"
  },
  piccadilly: {
    displayName: "Piccadilly",
    colour: "#10069f"
  },
  victoria: {
    displayName: "Victoria",
    colour: "#00a3e0"
  },
  waterlooAndCity: {
    displayName: "Waterloo & City",
    colour: "#6eceb2"
  },
} as const satisfies Record<string, Line>;

type Station = {
  displayName: string
  lines: (keyof typeof Lines)[]
};

export const Stations = {
  actonTown: { displayName: "Acton Town", lines: ["district", "piccadilly"] },
  aldgate: { displayName: "Aldgate", lines: ["metropolitan", "circle"] },
  aldgateEast: { displayName: "Aldgate East", lines: ["hammersmithAndCity", "district"] },
  alperton: { displayName: "Alperton", lines: ["piccadilly"] },
  amersham: { displayName: "Amersham", lines: ["metropolitan"] },
  angel: { displayName: "Angel", lines: ["northern"] },
  archway: { displayName: "Archway", lines: ["northern"] },
  arnosGrove: { displayName: "Arnos Grove", lines: ["piccadilly"] },
  arsenal: { displayName: "Arsenal", lines: ["piccadilly"] },

  bakerStreet: { displayName: "Baker Street", lines: ["metropolitan", "bakerloo", "circle", "jubilee", "hammersmithAndCity"] },
  balham: { displayName: "Balham", lines: ["northern"] },
  bank: { displayName: "Bank", lines: ["waterlooAndCity", "northern", "central"] },
  barbican: { displayName: "Barbican", lines: ["metropolitan", "circle", "hammersmithAndCity"] },
  barking: { displayName: "Barking", lines: ["district", "hammersmithAndCity"] },
  barkingside: { displayName: "Barkingside", lines: ["central"] },
  baronsCourt: { displayName: "Barons Court", lines: ["district", "piccadilly"] },
  batterseaPowerStation: { displayName: "Battersea Power Station", lines: ["northern"] },
  bayswater: { displayName: "Bayswater", lines: ["district", "circle"] },
  becontree: { displayName: "Becontree", lines: ["district"] },
  belsizePark: { displayName: "Belsize Park", lines: ["northern"] },
  bermondsey: { displayName: "Bermondsey", lines: ["jubilee"] },
  bethnalGreen: { displayName: "Bethnal Green", lines: ["central"] },
  blackfriars: { displayName: "Blackfriars", lines: ["district", "circle"] },
  blackhorseRoad: { displayName: "Blackhorse Road", lines: ["victoria"] },
  bondStreet: { displayName: "Bond Street", lines: ["central", "jubilee"] },
  borough: { displayName: "Borough", lines: ["northern"] },
  bostonManor: { displayName: "Boston Manor", lines: ["piccadilly"] },
  boundsGreen: { displayName: "Bounds Green", lines: ["piccadilly"] },
  bowRoad: { displayName: "Bow Road", lines: ["district", "hammersmithAndCity"] },
  brentCross: { displayName: "Brent Cross", lines: ["northern"] },
  brixton: { displayName: "Brixton", lines: ["victoria"] },
  bromleyByBow: { displayName: "Bromley-by-Bow", lines: ["district", "hammersmithAndCity"] },
  buckhurstHill: { displayName: "Buckhurst Hill", lines: ["central"] },
  burntOak: { displayName: "Burnt Oak", lines: ["northern"] },

  caledonianRoad: { displayName: "Caledonian Road", lines: ["piccadilly"] },
  camdenTown: { displayName: "Camden Town", lines: ["northern"] },
  canadaWater: { displayName: "Canada Water", lines: ["jubilee"] },
  canaryWharf: { displayName: "Canary Wharf", lines: ["jubilee"] },
  canningTown: { displayName: "Canning Town", lines: ["jubilee"] },
  cannonStreet: { displayName: "Cannon Street", lines: ["district", "circle"] },
  canonsPark: { displayName: "Canons Park", lines: ["jubilee"] },
  chalfontAndLatimer: { displayName: "Chalfont & Latimer", lines: ["metropolitan"] },
  chalkFarm: { displayName: "Chalk Farm", lines: ["northern"] },
  chanceryLane: { displayName: "Chancery Lane", lines: ["central"] },
  charingCross: { displayName: "Charing Cross", lines: ["bakerloo", "northern"] },
  chesham: { displayName: "Chesham", lines: ["metropolitan"] },
  chigwell: { displayName: "Chigwell", lines: ["central"] },
  chiswickPark: { displayName: "Chiswick Park", lines: ["district"] },
  chorleywood: { displayName: "Chorleywood", lines: ["metropolitan"] },
  claphamCommon: { displayName: "Clapham Common", lines: ["northern"] },
  claphamNorth: { displayName: "Clapham North", lines: ["northern"] },
  claphamSouth: { displayName: "Clapham South", lines: ["northern"] },
  cockfosters: { displayName: "Cockfosters", lines: ["piccadilly"] },
  colindale: { displayName: "Colindale", lines: ["northern"] },
  colliersWood: { displayName: "Colliers Wood", lines: ["northern"] },
  coventGarden: { displayName: "Covent Garden", lines: ["piccadilly"] },
  croxley: { displayName: "Croxley", lines: ["metropolitan"] },

  dagenhamEast: { displayName: "Dagenham East", lines: ["district"] },
  dagenhamHeathway: { displayName: "Dagenham Heathway", lines: ["district"] },
  debden: { displayName: "Debden", lines: ["central"] },
  dollisHill: { displayName: "Dollis Hill", lines: ["jubilee"] },

  ealingBroadway: { displayName: "Ealing Broadway", lines: ["district", "central"] },
  ealingCommon: { displayName: "Ealing Common", lines: ["district", "piccadilly"] },
  earlsCourt: { displayName: "Earl's Court", lines: ["district", "piccadilly"] },
  eastActon: { displayName: "East Acton", lines: ["central"] },
  eastFinchley: { displayName: "East Finchley", lines: ["northern"] },
  eastHam: { displayName: "East Ham", lines: ["district", "hammersmithAndCity"] },
  eastPutney: { displayName: "East Putney", lines: ["district"] },
  eastcote: { displayName: "Eastcote", lines: ["metropolitan", "piccadilly"] },
  edgware: { displayName: "Edgware", lines: ["northern"] },
  edgwareRoad1: { displayName: "Edgware Road", lines: ["bakerloo"] },
  edgwareRoad2: { displayName: "Edgware Road", lines: ["hammersmithAndCity", "district", "circle"] },
  elephantAndCastle: { displayName: "Elephant & Castle", lines: ["northern", "bakerloo"] },
  elmPark: { displayName: "Elm Park", lines: ["district"] },
  embankment: { displayName: "Embankment", lines: ["district", "bakerloo", "northern", "circle"] },
  epping: { displayName: "Epping", lines: ["central"] },
  euston: { displayName: "Euston", lines: ["northern", "victoria"] },
  eustonSquare: { displayName: "Euston Square", lines: ["metropolitan", "circle", "hammersmithAndCity"] },

  fairlop: { displayName: "Fairlop", lines: ["central"] },
  farringdon: { displayName: "Farringdon", lines: ["metropolitan", "circle", "hammersmithAndCity"] },
  finchleyCentral: { displayName: "Finchley Central", lines: ["northern"] },
  finchleyRoad: { displayName: "Finchley Road", lines: ["metropolitan", "jubilee"] },
  finsburyPark: { displayName: "Finsbury Park", lines: ["piccadilly", "victoria"] },
  fulhamBroadway: { displayName: "Fulham Broadway", lines: ["district"] },

  gantsHill: { displayName: "Gants Hill", lines: ["central"] },
  gloucesterRoad: { displayName: "Gloucester Road", lines: ["district", "piccadilly", "circle"] },
  goldersGreen: { displayName: "Golders Green", lines: ["northern"] },
  goldhawkRoad: { displayName: "Goldhawk Road", lines: ["hammersmithAndCity", "circle"] },
  goodgeStreet: { displayName: "Goodge Street", lines: ["northern"] },
  grangeHill: { displayName: "Grange Hill", lines: ["central"] },
  greatPortlandStreet: { displayName: "Great Portland Street", lines: ["metropolitan", "circle", "hammersmithAndCity"] },
  greenford: { displayName: "Greenford", lines: ["central"] },
  greenPark: { displayName: "Green Park", lines: ["piccadilly", "victoria", "jubilee"] },
  gunnersbury: { displayName: "Gunnersbury", lines: ["district"] },

  hainault: { displayName: "Hainault", lines: ["central"] },
  hammersmith1: { displayName: "Hammersmith", lines: ["district", "piccadilly"] },
  hammersmith2: { displayName: "Hammersmith", lines: ["hammersmithAndCity", "circle"] },
  hampstead: { displayName: "Hampstead", lines: ["northern"] },
  hangerLane: { displayName: "Hanger Lane", lines: ["central"] },
  harlesden: { displayName: "Harlesden", lines: ["bakerloo"] },
  harrowAndWealdstone: { displayName: "Harrow & Wealdstone", lines: ["bakerloo"] },
  harrowOnTheHill: { displayName: "Harrow-on-the-Hill", lines: ["metropolitan"] },
  hattonCross: { displayName: "Hatton Cross", lines: ["piccadilly"] },
  heathrowTerminalsTwoAndThree: { displayName: "Heathrow Terminals 2 & 3", lines: ["piccadilly"] },
  heathrowTerminalFour: { displayName: "Heathrow Terminal 4", lines: ["piccadilly"] },
  heathrowTerminalFive: { displayName: "Heathrow Terminal 5", lines: ["piccadilly"] },
  hendonCentral: { displayName: "Hendon Central", lines: ["northern"] },
  highBarnet: { displayName: "High Barnet", lines: ["northern"] },
  highburyAndIslington: { displayName: "Highbury & Islington", lines: ["victoria"] },
  highgate: { displayName: "Highgate", lines: ["northern"] },
  highStreetKensington: { displayName: "High Street Kensington", lines: ["district", "circle"] },
  hillingdon: { displayName: "Hillingdon", lines: ["metropolitan", "piccadilly"] },
  holborn: { displayName: "Holborn", lines: ["central", "piccadilly"] },
  hollandPark: { displayName: "Holland Park", lines: ["central"] },
  hollowayRoad: { displayName: "Holloway Road", lines: ["piccadilly"] },
  hornchurch: { displayName: "Hornchurch", lines: ["district"] },
  hounslowCentral: { displayName: "Hounslow Central", lines: ["piccadilly"] },
  hounslowEast: { displayName: "Hounslow East", lines: ["piccadilly"] },
  hounslowWest: { displayName: "Hounslow West", lines: ["piccadilly"] },
  hydeParkCorner: { displayName: "Hyde Park Corner", lines: ["piccadilly"] },

  ickenham: { displayName: "Ickenham", lines: ["metropolitan", "piccadilly"] },

  kennington: { displayName: "Kennington", lines: ["northern"] },
  kensalGreen: { displayName: "Kensal Green", lines: ["bakerloo"] },
  kensingtonOlympia: { displayName: "Kensington (Olympia)", lines: ["district"] },
  kentishTown: { displayName: "Kentish Town", lines: ["northern"] },
  kenton: { displayName: "Kenton", lines: ["bakerloo"] },
  kewGardens: { displayName: "Kew Gardens", lines: ["district"] },
  kilburn: { displayName: "Kilburn", lines: ["jubilee"] },
  kilburnPark: { displayName: "Kilburn Park", lines: ["bakerloo"] },
  kingsbury: { displayName: "Kingsbury", lines: ["jubilee"] },
  kingsCrossStPancras: { displayName: "King's Cross St Pancras", lines: ["metropolitan", "northern", "piccadilly", "circle", "victoria", "hammersmithAndCity"] },
  knightsbridge: { displayName: "Knightsbridge", lines: ["piccadilly"] },

  ladbrokeGrove: { displayName: "Ladbroke Grove", lines: ["hammersmithAndCity", "circle"] },
  lambethNorth: { displayName: "Lambeth North", lines: ["bakerloo"] },
  lancasterGate: { displayName: "Lancaster Gate", lines: ["central"] },
  latimerRoad: { displayName: "Latimer Road", lines: ["hammersmithAndCity", "circle"] },
  leicesterSquare: { displayName: "Leicester Square", lines: ["piccadilly", "northern"] },
  leyton: { displayName: "Leyton", lines: ["central"] },
  leytonstone: { displayName: "Leytonstone", lines: ["central"] },
  liverpoolStreet: { displayName: "Liverpool Street", lines: ["metropolitan", "central", "circle", "hammersmithAndCity"] },
  londonBridge: { displayName: "London Bridge", lines: ["northern", "jubilee"] },
  loughton: { displayName: "Loughton", lines: ["central"] },

  maidaVale: { displayName: "Maida Vale", lines: ["bakerloo"] },
  manorHouse: { displayName: "Manor House", lines: ["piccadilly"] },
  mansionHouse: { displayName: "Mansion House", lines: ["district", "circle"] },
  marbleArch: { displayName: "Marble Arch", lines: ["central"] },
  marylebone: { displayName: "Marylebone", lines: ["bakerloo"] },
  mileEnd: { displayName: "Mile End", lines: ["district", "hammersmithAndCity", "central"] },
  millHillEast: { displayName: "Mill Hill East", lines: ["northern"] },
  monument: { displayName: "Monument", lines: ["district", "circle"] },
  moorgate: { displayName: "Moorgate", lines: ["metropolitan", "northern", "circle", "hammersmithAndCity"] },
  moorPark: { displayName: "Moor Park", lines: ["metropolitan"] },
  morden: { displayName: "Morden", lines: ["northern"] },
  morningtonCrescent: { displayName: "Mornington Crescent", lines: ["northern"] },

  neasden: { displayName: "Neasden", lines: ["jubilee"] },
  newburyPark: { displayName: "Newbury Park", lines: ["central"] },
  nineElms: { displayName: "Nine Elms", lines: ["northern"] },
  northActon: { displayName: "North Acton", lines: ["central"] },
  northEaling: { displayName: "North Ealing", lines: ["piccadilly"] },
  northHarrow: { displayName: "northHarrow", lines: ["metropolitan"] },
  northWembley: { displayName: "North Wembley", lines: ["bakerloo"] },
  northfields: { displayName: "Northfields", lines: ["piccadilly"] },
  northolt: { displayName: "Northolt", lines: ["central"] },
  northwickPark: { displayName: "Northwick Park", lines: ["metropolitan"] },
  northwood: { displayName: "Northwood", lines: ["metropolitan"] },
  northwoodHills: { displayName: "Northwood Hills", lines: ["metropolitan"] },
  nottingHillGate: { displayName: "Notting Hill Gate", lines: ["district", "central", "circle"] },

  oakwood: { displayName: "Oakwood", lines: ["piccadilly"] },
  oldStreet: { displayName: "Old Street", lines: ["northern"] },
  osterley: { displayName: "Osterley", lines: ["piccadilly"] },
  oval: { displayName: "Oval", lines: ["northern"] },
  oxfordCircus: { displayName: "Oxford Circus", lines: ["central", "bakerloo", "victoria"] },

  paddington: { displayName: "Paddington", lines: ["district", "circle", "bakerloo", "hammersmithAndCity"] },
  parkRoyal: { displayName: "Park Royal", lines: ["piccadilly"] },
  parsonsGreen: { displayName: "Parsons Green", lines: ["district"] },
  perivale: { displayName: "Perivale", lines: ["central"] },
  piccadillyCircus: { displayName: "Piccadilly Circus", lines: ["bakerloo", "piccadilly"] },
  pimlico: { displayName: "Pimlico", lines: ["victoria"] },
  pinner: { displayName: "Pinner", lines: ["metropolitan"] },
  plaistow: { displayName: "Plaistow", lines: ["district", "hammersmithAndCity"] },
  prestonRoad: { displayName: "Preston Road", lines: ["metropolitan"] },

  queensPark: { displayName: "Queen's Park", lines: ["bakerloo"] },
  queensbury: { displayName: "Queensbury", lines: ["jubilee"] },
  queensway: { displayName: "Queensway", lines: ["central"] },

  ravenscourtPark: { displayName: "Ravenscourt Park", lines: ["district"] },
  raynersLane: { displayName: "Rayners Lane", lines: ["metropolitan", "piccadilly"] },
  redbridge: { displayName: "Redbridge", lines: ["central"] },
  regentsPark: { displayName: "Regents Park", lines: ["bakerloo"] },
  richmond: { displayName: "Richmond", lines: ["district"] },
  rickmansworth: { displayName: "Rickmansworth", lines: ["metropolitan"] },
  rodingValley: { displayName: "Roding Valley", lines: ["central"] },
  royalOak: { displayName: "Royal Oak", lines: ["hammersmithAndCity", "circle"] },
  ruislip: { displayName: "Ruislip", lines: ["metropolitan", "piccadilly"] },
  ruislipGardens: { displayName: "Ruislip Gardens", lines: ["central"] },
  ruislipManor: { displayName: "Ruislip Manor", lines: ["metropolitan", "piccadilly"] },
  russellSquare: { displayName: "Russell Square", lines: ["piccadilly"] },

  stJamesPark: { displayName: "St James's Park", lines: ["district", "circle"] },
  stJohnsWood: { displayName: "St John's Wood", lines: ["jubilee"] },
  stPauls: { displayName: "St Paul's", lines: ["central"] },
  sevenSisters: { displayName: "Seven Sisters", lines: ["victoria"] },
  shepherdsBush: { displayName: "Shepherd's Bush", lines: ["central"] },
  shepherdsBushMarket: { displayName: "Shepherd's Bush Market", lines: ["hammersmithAndCity", "circle"] },
  sloaneSquare: { displayName: "Sloane Square", lines: ["district", "circle"] },
  snaresbrook: { displayName: "Snaresbrook", lines: ["central"] },
  southEaling: { displayName: "South Ealing", lines: ["piccadilly"] },
  southHarrow: { displayName: "South Harrow", lines: ["piccadilly"] },
  southKensington: { displayName: "South Kensington", lines: ["district", "circle", "piccadilly"] },
  southKenton: { displayName: "South Kenton", lines: ["bakerloo"] },
  southRuislip: { displayName: "South Ruislip", lines: ["central"] },
  southWimbledon: { displayName: "South Wimbledon", lines: ["northern"] },
  southWoodford: { displayName: "South Woodford", lines: ["central"] },
  southfields: { displayName: "Southfields", lines: ["district"] },
  southgate: { displayName: "Southgate", lines: ["piccadilly"] },
  southwark: { displayName: "Southwark", lines: ["jubilee"] },
  stamfordBrook: { displayName: "Stamford Brook", lines: ["district"] },
  stanmore: { displayName: "Stanmore", lines: ["jubilee"] },
  stepneyGreen: { displayName: "", lines: ["district", "hammersmithAndCity"] },
  stockwell: { displayName: "Stockwell", lines: ["victoria", "northern"] },
  stonebridgePark: { displayName: "Stonebridge park", lines: ["bakerloo"] },
  stratford: { displayName: "Stratford", lines: ["central", "jubilee"] },
  sudburyHill: { displayName: "Sudbury Hill", lines: ["piccadilly"] },
  sudburyTown: { displayName: "Sudbury Town", lines: ["piccadilly"] },
  swissCottage: { displayName: "Swiss Cottage", lines: ["jubilee"] },

  temple: { displayName: "Temple", lines: ["district", "circle"] },
  theydonBois: { displayName: "Theydon Bois", lines: ["central"] },
  tootingBec: { displayName: "Theydon Bois", lines: ["northern"] },
  tootingBroadway: { displayName: "Tooting Broadway", lines: ["northern"] },
  tottenhamCourtRoad: { displayName: "Tottenham Court Road", lines: ["northern", "central"] },
  tottenhamHale: { displayName: "Tottenham Hale", lines: ["victoria"] },
  totteridgeAndWhetstone: { displayName: "Totteridge & Whetstone", lines: ["northern"] },
  towerHill: { displayName: "Tower Hill", lines: ["district", "circle"] },
  tufnellPark: { displayName: "Tufnell Park", lines: ["northern"] },
  turnhamGreen: { displayName: "Turnham Green", lines: ["district", "piccadilly"] },
  turnpikeLane: { displayName: "Turnpike Lane", lines: ["piccadilly"] },

  upminster: { displayName: "Upminster", lines: ["district"] },
  upminsterBridge: { displayName: "Upminster Bridge", lines: ["district"] },
  upney: { displayName: "Upney", lines: ["district"] },
  uptonPark: { displayName: "Upton Park", lines: ["district"] },
  uxbridge: { displayName: "Uxbridge", lines: ["metropolitan", "piccadilly"] },

  vauxhall: { displayName: "Vauxhall;", lines: ["victoria"] },
  victoria: { displayName: "Victoria", lines: ["victoria", "district", "circle"] },

  walthamstowCentral: { displayName: "Walthamstow Central", lines: ["victoria"] },
  wanstead: { displayName: "Wansted", lines: ["central"] },
  warrenStreet: { displayName: "Warren Street", lines: ["northern", "victoria"] },
  warwickAvenue: { displayName: "Warwick Avenue", lines: ["bakerloo"] },
  waterloo: { displayName: "Waterloo", lines: ["waterlooAndCity", "bakerloo", "northern", "jubilee"] },
  watford: { displayName: "Watford", lines: ["metropolitan"] },
  wembleyCentral: { displayName: "Wembley Central", lines: ["bakerloo"] },
  wembleyPark: { displayName: "Wembley Park", lines: ["metropolitan", "jubilee"] },
  westActon: { displayName: "West Acton", lines: ["central"] },
  westbrompton: { displayName: "West Brompton", lines: ["district"] },
  westFichley: { displayName: "West Finchley", lines: ["northern"] },
  westHam: { displayName: "West Ham", lines: ["district", "hammersmithAndCity", "jubilee"] },
  westHampstead: { displayName: "West Hampstead", lines: ["jubilee"] },
  westHarrow: { displayName: "West Harrow", lines: ["metropolitan"] },
  westKensington: { displayName: "West Kensington", lines: ["district"] },
  westRuislip: { displayName: "West Ruislip", lines: ["central"] },
  westbournePark: { displayName: "Westbourne Park", lines: ["hammersmithAndCity", "circle"] },
  westminster: { displayName: "Westminster", lines: ["district", "circle", "jubilee"] },
  whiteCity: { displayName: "White City", lines: ["central"] },
  whitechapel: { displayName: "Whitechapel", lines: ["district", "hammersmithAndCity"] },
  willesdenGreen: { displayName: "Willesden Green", lines: ["jubilee"] },
  willesdenJunction: { displayName: "WillesdenJunction", lines: ["bakerloo"] },
  wimbledon: { displayName: "Wimbledon", lines: ["district"] },
  wimbledonPark: { displayName: "Wimbledon Park", lines: ["district"] },
  woodGreen: { displayName: "Wood Green", lines: ["piccadilly"] },
  woodford: { displayName: "Woodford", lines: ["central"] },
  woodsidePark: { displayName: "Woodside Park", lines: ["northern"] },
} as const satisfies Record<string, Station>;